### ISSUE TITLE
Some keys do not work

### ISSUE THREAD

**Issue by johenning** [hpi-swa/graalsqueak#56]
On Windows: 
- @ typed via german keyboard layout (Alt-Gr + q)
- ' typed with us international with dead keys

**Comment by fmateoc** [comment]
I just tried to add a different language on Windows (Romanian, in addition to En-US).
After switching the input method to Romanian, the Windows programs would accept Romanian characters as per a Romanian keyboard, but Squeak itself did not. It displayed the special characters neither as per the Romanian keyboard nor as per the En-US keyboard. Anyway, this seems to be a Squeak bug, not a GraalSqueak bug, which behaves the same way as Squeak

**Comment by fmateoc** [comment]
For a concrete example, the character ă is displayed instead of [ when the input method is Romanian (instead of En-US). In Squeak the same keypress is displayed as ?

**Comment by fniephaus** [comment]
Thanks for looking into this. We should make sure that GraalSqueak provides the same input as the default Squeak VM, with priority for English of course. The rest should be addressed by the Squeak team.

Could you check that the most important special characters and modifier keys are handled as expected on Windows with en-US?

**Comment by fmateoc** [comment]
actually, I did find a couple of bugs in the keyboard handling code, and the issue of Squeak printing ? is likely related to fonts (the character has the correct value 259 and the string is a WideString), so perhaps the fixes will help. Then again, the bug description is extremely terse and I don't understand it...

**Comment by fniephaus** [comment]
No need to worry about the bug description, things got a lot better in the meantime. I was going to close this, because I think we fixed most issues and no one is complaining at the moment. But since I have limited access to a Windows machine, I just wanted to double check with you :)

**Comment by fmateoc** [comment]
I just pushed a commit related to this

**Comment by fniephaus** [comment]
Thanks, I cherry-picked your commit (https://github.com/hpi-swa/graalsqueak/commit/e371858fac17381e9ef0f10e1f5f2ee9800d01cd) and pushed https://github.com/hpi-swa/graalsqueak/commit/f6f6aa4da960cd97a7b52f28373e4771d6c1e12e. Closing this for now...
