### ISSUE TITLE
Java <-> Squeak byte array conversion issues

### ISSUE THREAD

**Issue by marschall** [hpi-swa/graalsqueak#78]
I'm struggling with passing byte arrays between Java and Squeak. The issue is that 0xFF is represented as 255 in Squeak and -1 in Java as Java only has signed bytes and bytes in Squeak are unsigned.

The following works:
```st
(Java type: 'java.net.InetAddress')
	getByAddress: #[127 0 0 1]
```

but this fails

```st
(Java type: 'java.net.InetAddress')
	getByAddress: #[192 168 0 1]
```

**Comment by fniephaus** [comment]
Another interop bug, thanks for reporting! A fix is on the way:

![image](https://user-images.githubusercontent.com/2368856/67243590-96781280-f460-11e9-9211-f53625622a7c.png)

**Comment by fniephaus** [comment]
A fix is on `dev` and will ship with the next release.
