### ISSUE TITLE
Manually built component is not recognized when running in eclipse

### ISSUE THREAD

**Issue by mahsohn** [hpi-swa/graalsqueak#87]
I am trying to debug graalsqueak in eclipse, when I run make_component.sh and install it then try to run GraalSqueakLauncher I get the error "A language with id 'smalltalk' is not installed". When I install the component from the release it works fine, what is strange is that running "mx squeak" works with the custom component but not in eclipse. There seems to be some difference between the release graalsqueak.jar and the graalsqueak.jar being compiled but I don't know what it is, I have tried compiling with different jdk versions including 1.8 and still no luck.

**Comment by fniephaus** [comment]
Hi @mahsohn,
I recommend against installing the component if you want to develop GraalSqueak, it's really only for users. Also note that you don't have to run GraalSqueak on GraalVM during development. Performance is reasonable if you just use an off-the-shelf JDK8. Besides, if `mx squeak` works for you, you should be able to run `mx -d squeak`, which starts the VM in debug mode. You can then connect your Eclipse debugger.

Hope this helps... if it doesn't please, reopen the issue. :)

Fabio
